import { useState } from 'react'
import { formatByte } from '../graph/model'
import { formatOffset } from '../forensics/model'
import type { Trace } from '../trace/types'
import { Inspector } from './Inspector'
import type { Selection } from './FragmentGraph'
type Props={trace:Trace;selection:Selection;onSelect:(s:Selection)=>void}
export function EvidencePanels(p:Props){const[tab,setTab]=useState<'evidence'|'repairs'|'format'>('evidence');const inspect=p.selection?.kind==='fragment'||p.selection?.kind==='edge'?p.selection:undefined;return <aside className="panel-shell"><div className="tabs">{(['evidence','repairs','format']as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='evidence'?<Inspector trace={p.trace} selection={inspect} onSelect={p.onSelect}/>:tab==='repairs'?<Repairs {...p}/>:<Format {...p}/>}</aside>}
function Repairs({trace,onSelect}:Props){return <div className="panel-body"><h2>Repair evidence</h2><div className="metric-line">Total <b>{trace.repairs.length}</b> · Consensus <b>{trace.repairs.filter(r=>r.stage==='consensus').length}</b> · PNG CRC <b>{trace.repairs.filter(r=>r.stage==='png_crc').length}</b></div><div className="metric-line">Unresolved ambiguities <b>{trace.unresolved_ambiguities}</b></div>{trace.repairs.length===0?<p>No repair events were recorded for this reconstruction.</p>:trace.repairs.map((r,i)=><button className="event-card" onClick={()=>onSelect({kind:'repair',index:i})} key={i}><b>{r.stage==='png_crc'?'PNG CRC-guided':'Consensus'} · {formatOffset(r.position,6)}</b><span>{formatByte(r.before)} → {formatByte(r.after)}</span><small>{r.stage==='png_crc'?`CRC-consistent · ${r.candidates_tested} candidates`:`${r.support} / ${r.observations} observations`}</small></button>)}</div>}
function Format({trace,onSelect}:Props){if(trace.format.type==='none')return <div className="panel-body"><h2>Format evidence</h2><p>No format-specific analyzer was used.</p></div>;return <div className="panel-body"><h2>PNG evidence</h2><div className="metric-line">Signature <b>{trace.format.signature_valid?'VALID':'INVALID'}</b> · Structure <b>{trace.format.structurally_valid?'VALID':'INVALID'}</b></div><div className="metric-line">Dimensions <b>{trace.format.width??'—'} × {trace.format.height??'—'}</b></div><div className="metric-line">Chunks <b>{trace.format.chunks.length}</b> · CRC <b>{trace.format.valid_crc_count} valid / {trace.format.invalid_crc_count} invalid</b></div><table><thead><tr><th>#</th><th>Offset</th><th>Type</th><th>Length</th><th>CRC</th></tr></thead><tbody>{trace.format.chunks.map((c,i)=><tr className={c.crc_valid?'':'invalid'} onClick={()=>onSelect({kind:'chunk',index:i})} key={c.index}><td>{c.index}</td><td>{formatOffset(c.offset,6)}</td><td>{c.type}</td><td>{c.length}</td><td>{c.crc_valid?'VALID':'INVALID'}</td></tr>)}</tbody></table></div>}
